name: genpass
description: A password generator app written by Flutter/Dart.

publish_to: 'none'

version: 2.4.0+2040000

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  logging: ^1.0.2
  shared_preferences: ^2.0.9

dev_dependencies:
  fake_async: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/appicon.png
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/SourceCodePro-Regular.ttf
